//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotify.ObjectModel.Serialization.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spotify.ObjectModel.Serialization.Tests.Resources.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;album_type&quot;:&quot;album&quot;,&quot;artists&quot;:[{&quot;external_urls&quot;:{&quot;spotify&quot;:&quot;https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc&quot;},&quot;href&quot;:&quot;https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc&quot;,&quot;id&quot;:&quot;4pb4rqWSoGUgxm63xmJ8xc&quot;,&quot;name&quot;:&quot;Madeon&quot;,&quot;type&quot;:&quot;artist&quot;,&quot;uri&quot;:&quot;spotify:artist:4pb4rqWSoGUgxm63xmJ8xc&quot;}],&quot;available_markets&quot;:[&quot;AD&quot;,&quot;AE&quot;,&quot;AL&quot;,&quot;AR&quot;,&quot;AT&quot;,&quot;AU&quot;,&quot;BA&quot;,&quot;BE&quot;,&quot;BG&quot;,&quot;BH&quot;,&quot;BO&quot;,&quot;BR&quot;,&quot;BY&quot;,&quot;CA&quot;,&quot;CH&quot;,&quot;CL&quot;,&quot;CO&quot;,&quot;CR&quot;,&quot;CY&quot;,&quot;CZ&quot;,&quot;DE&quot;,&quot;DK&quot;,&quot;DO&quot;,&quot;DZ&quot;,&quot;EC&quot;,&quot;EE&quot;,&quot;EG&quot;,&quot;ES&quot;,&quot;FI&quot;,&quot;FR&quot;,&quot;GB&quot;,&quot;GR&quot;,&quot;GT&quot;,&quot;HK&quot;,&quot;HN&quot;,&quot;HR&....
        /// </summary>
        internal static string AlbumJson {
            get {
                return ResourceManager.GetString("AlbumJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;external_urls&quot;:{&quot;spotify&quot;:&quot;https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc&quot;},&quot;followers&quot;:{&quot;href&quot;:null,&quot;total&quot;:542633},&quot;genres&quot;:[&quot;big room&quot;,&quot;complextro&quot;,&quot;edm&quot;,&quot;electro house&quot;,&quot;electropop&quot;,&quot;filter house&quot;,&quot;future bass&quot;,&quot;nantes indie&quot;],&quot;href&quot;:&quot;https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc&quot;,&quot;id&quot;:&quot;4pb4rqWSoGUgxm63xmJ8xc&quot;,&quot;images&quot;:[{&quot;height&quot;:640,&quot;url&quot;:&quot;https://i.scdn.co/image/426e0d784cfc0dfe8f3275e32850223232835c14&quot;,&quot;width&quot;:640},{&quot;height&quot;:320,&quot;url&quot;:&quot;https://i.scdn.co/image/d12113789d3953523b7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArtistJson {
            get {
                return ResourceManager.GetString("ArtistJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;audio_preview_url&quot;:&quot;https://p.scdn.co/mp3-preview/f13368629f9d4f164e2ad486028e4504aa616bed&quot;,&quot;description&quot;:&quot;Waveform with Marques Brownlee, coming soon! From the mind of Marques Brownlee, better known as MKBHD, comes Waveform, a tech podcast for the gadget lovers and tech heads. MKBHD has made a name for himself on Youtube reviewing everything from Apple iPhones, Samsung Galaxys, the newest laptops, digital cameras and even Tesla electric cars. Pulling from over 10 years of experience covering the tech ind [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EpisodeJson {
            get {
                return ResourceManager.GetString("EpisodeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;collaborative&quot;:false,&quot;description&quot;:&quot;A look in to the mind of Dimension, updated monthly. Follow on &lt;a href=\&quot;https://open.spotify.com/artist/1QMgre3BHX161ZHtWMUu6S?si=N9H6fAStQO-hnFHupfgJxg\&quot;&gt;Spotify&lt;/a&gt;.&quot;,&quot;external_urls&quot;:{&quot;spotify&quot;:&quot;https://open.spotify.com/playlist/2yPxcfVbIHU7wDrS3NHOpF&quot;},&quot;followers&quot;:{&quot;href&quot;:null,&quot;total&quot;:3448},&quot;href&quot;:&quot;https://api.spotify.com/v1/playlists/2yPxcfVbIHU7wDrS3NHOpF&quot;,&quot;id&quot;:&quot;2yPxcfVbIHU7wDrS3NHOpF&quot;,&quot;images&quot;:[{&quot;height&quot;:null,&quot;url&quot;:&quot;https://i.scdn.co/image/ab67706c0000bebbbf6ba81 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlaylistJson {
            get {
                return ResourceManager.GetString("PlaylistJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;album_type&quot;:&quot;album&quot;,&quot;artists&quot;:[{&quot;external_urls&quot;:{&quot;spotify&quot;:&quot;https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc&quot;},&quot;href&quot;:&quot;https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc&quot;,&quot;id&quot;:&quot;4pb4rqWSoGUgxm63xmJ8xc&quot;,&quot;name&quot;:&quot;Madeon&quot;,&quot;type&quot;:&quot;artist&quot;,&quot;uri&quot;:&quot;spotify:artist:4pb4rqWSoGUgxm63xmJ8xc&quot;}],&quot;available_markets&quot;:[&quot;AD&quot;,&quot;AE&quot;,&quot;AL&quot;,&quot;AR&quot;,&quot;AT&quot;,&quot;AU&quot;,&quot;BA&quot;,&quot;BE&quot;,&quot;BG&quot;,&quot;BH&quot;,&quot;BO&quot;,&quot;BR&quot;,&quot;BY&quot;,&quot;CA&quot;,&quot;CH&quot;,&quot;CL&quot;,&quot;CO&quot;,&quot;CR&quot;,&quot;CY&quot;,&quot;CZ&quot;,&quot;DE&quot;,&quot;DK&quot;,&quot;DO&quot;,&quot;DZ&quot;,&quot;EC&quot;,&quot;EE&quot;,&quot;EG&quot;,&quot;ES&quot;,&quot;FI&quot;,&quot;FR&quot;,&quot;GB&quot;,&quot;GR&quot;,&quot;GT&quot;,&quot;HK&quot;,&quot;HN&quot;,&quot;HR&....
        /// </summary>
        internal static string SimplifiedAlbumJson {
            get {
                return ResourceManager.GetString("SimplifiedAlbumJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;external_urls&quot;:{&quot;spotify&quot;:&quot;https://open.spotify.com/artist/4pb4rqWSoGUgxm63xmJ8xc&quot;},&quot;href&quot;:&quot;https://api.spotify.com/v1/artists/4pb4rqWSoGUgxm63xmJ8xc&quot;,&quot;id&quot;:&quot;4pb4rqWSoGUgxm63xmJ8xc&quot;,&quot;name&quot;:&quot;Madeon&quot;,&quot;type&quot;:&quot;artist&quot;,&quot;uri&quot;:&quot;spotify:artist:4pb4rqWSoGUgxm63xmJ8xc&quot;}.
        /// </summary>
        internal static string SimplifiedArtistJson {
            get {
                return ResourceManager.GetString("SimplifiedArtistJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;audio_preview_url&quot;:&quot;https://p.scdn.co/mp3-preview/f13368629f9d4f164e2ad486028e4504aa616bed&quot;,&quot;description&quot;:&quot;Waveform with Marques Brownlee, coming soon! From the mind of Marques Brownlee, better known as MKBHD, comes Waveform, a tech podcast for the gadget lovers and tech heads. MKBHD has made a name for himself on Youtube reviewing everything from Apple iPhones, Samsung Galaxys, the newest laptops, digital cameras and even Tesla electric cars. Pulling from over 10 years of experience covering the tech ind [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimplifiedEpisodeJson {
            get {
                return ResourceManager.GetString("SimplifiedEpisodeJson", resourceCulture);
            }
        }
    }
}
